name: Update UI
main: SkulZTeams\Join UI X\main
api: 4.0.0
author: SkulZOnTheYT
version: 1.0.0

commands:

  joinui:

    description: use Command Join UI X

    permission:joinui.use

permission:

  joinui.use:

    description: Permission Use Command Join Ui X

    default:true


